### ISSUE TITLE
Feedback on unrecognized barcode

### ISSUE THREAD

**Issue by alex95sandberg** [evpxregu/agiledevelopmentprocess#15]
Velocity: 2

**Comment by evpxregu** [comment]
We now show a line when there is an unrecognized barcode as shown in the image below.


![image](https://user-images.githubusercontent.com/4245456/39187616-1169789e-47ce-11e8-9b03-507c2e265b02.png)

**Comment by SebbeLind** [comment]
Was a few bugs, reopen.

**Comment by evpxregu** [comment]
unexpected complexity, needs a bit more work next sprint
